protocols = imap lmtp

log_path = /dev/stderr
info_log_path = /dev/stdout
debug_log_path = /dev/stdout

log_timestamp = "%Y-%m-%d %H:%M:%S "

disable_plaintext_auth = yes

auth_mechanisms = plain login

!include conf.d/*.conf
