Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes

UserID                  opendkim

Mode                    sv

Canonicalization        relaxed/simple

SignatureAlgorithm      rsa-sha256

KeyTable                /etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable

ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
