mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir

mail_uid = 5000
mail_gid = 5000

first_valid_uid = 5000
last_valid_uid = 5000
first_valid_gid = 5000
last_valid_gid = 5000

mail_privileged_group = vmail

maildir_copy_with_hardlinks = yes
